import { test, expect } from '@playwright/test';

test('owner can review connectors, import a patient and approve a mock communication', async ({ page }, testInfo) => {
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await page.getByLabel('Email').fill('owner@demo.optical');
  await page.getByLabel('Password').fill('OpticalDemo2026!');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Your practice, in focus' })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath('overview.png'), fullPage: true });
  await page.getByRole('button', { name: 'Data', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Plato Medical', exact: true })).toBeVisible();
  await expect(page.getByText('Unavailable', { exact: true })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath('data.png'), fullPage: true });
  await page.getByLabel('CSV or XLSX file').setInputFiles({ name: 'browser-patient.csv', mimeType: 'text/csv', buffer: Buffer.from('Patient ID,Full Name,Consent,Mobile,Last Exam\nBROWSER-1,Browser Test Patient,yes,89999998,2024-01-01') });
  await page.getByRole('button', { name: 'Inspect file' }).click();
  await page.getByRole('button', { name: 'Validate mapping' }).click();
  await expect(page.getByText('1 valid · 0 invalid · 0 duplicate candidates')).toBeVisible();
  await page.getByLabel('I have reviewed the preview and approve importing valid rows.').check();
  await page.getByRole('button', { name: 'Approve & import' }).click();
  await expect(page.getByRole('status')).toContainText('1 imported');
  await page.getByRole('button', { name: 'Opportunities', exact: true }).click();
  await page.getByLabel('Search patients').fill('Browser Test Patient');
  await page.getByRole('button', { name: 'Browser Test Patient', exact: true }).click();
  await page.getByRole('button', { name: 'Generate draft' }).click();
  await expect(page.getByLabel('Patient message')).toHaveValue(/Browser/);
  await page.getByRole('button', { name: 'Approve & queue' }).click();
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await page.getByRole('button', { name: 'Campaigns', exact: true }).click();
  await page.getByRole('button', { name: 'Recall · Browser Test Patient', exact: true }).click();
  await page.getByRole('button', { name: 'Send with mock provider' }).click();
  await expect(page.getByRole('dialog').getByText('Completed', { exact: true })).toBeVisible();
  await expect(page.getByRole('dialog').getByText('Delivered', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Close dialog' }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: 'Overview', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Your practice, in focus' })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath('mobile.png'), fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});
