import { useEffect,useRef,type ReactNode } from 'react';
import { X,ArrowUpRight,Inbox,LoaderCircle,Check,AlertCircle,ChevronRight } from 'lucide-react';
import { TYPES,initials,money,date,type Opportunity } from './lib';
export function Brand({small=false}:{small?:boolean}){return <div className={'brand '+(small?'small':'')}><span className="brand-mark"><i/><i/></span>{!small&&<span>optical<span className="brand-light">operator</span></span>}</div>}
export function Spinner(){return <div className="loading"><LoaderCircle size={25} className="spin"/><span>Bringing your practice into focus…</span></div>}
export function Empty({title,description,children}:{title:string;description:string;children?:ReactNode}){return <div className="empty"><span className="empty-icon"><Inbox size={26}/></span><h3>{title}</h3><p>{description}</p>{children}</div>}
export function ErrorBox({message}:{message:string}){return message?<div className="error-box" role="alert"><AlertCircle size={17}/><span>{message}</span></div>:null}
export function Badge({children,tone='neutral'}:{children:ReactNode;tone?:string}){return <span className={'badge '+tone}>{children}</span>}
export function Status({status}:{status:string}){return <Badge tone={['completed','delivered','approved'].includes(status)?'green':status==='draft'?'neutral':status==='new'?'blue':status==='failed'?'red':'amber'}><span className="status-dot"/>{status==='new'?'Open':status.charAt(0).toUpperCase()+status.slice(1)}</Badge>}
export function Avatar({name,index=0}:{name:string;index?:number}){return <span className={'avatar avatar-'+index%5}>{initials(name)}</span>}
export function Modal({title,subtitle,children,onClose,wide=false,drawer=false}:{title:string;subtitle?:string;children:ReactNode;onClose:()=>void;wide?:boolean;drawer?:boolean}){
  const ref=useRef<HTMLDialogElement>(null);
  useEffect(()=>{const el=ref.current;el?.showModal();document.body.style.overflow='hidden';return()=>{el?.close();document.body.style.overflow='';};},[]);
  return <dialog ref={ref} className={`modal ${wide?'wide':''} ${drawer?'drawer':''}`} onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose();}}><div className="modal-inner"><div className="modal-heading"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X size={20}/></button></div>{children}</div></dialog>;
}
export function PageHeading({eyebrow,title,description,children}:{eyebrow?:string;title:string;description:string;children?:ReactNode}){return <div className="page-heading"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1><p>{description}</p></div><div className="heading-actions">{children}</div></div>}
export function Metric({label,value,detail,icon,tone='green'}:{label:string;value:string;detail:string;icon:ReactNode;tone?:string}){return <div className="metric card"><div className="metric-label">{label}<span className={'metric-icon '+tone}>{icon}</span></div><div className="metric-value">{value}</div><div className="metric-detail">{detail}</div></div>}
export function OpportunityTable({items,onSelect,compact=false}:{items:Opportunity[];onSelect:(id:string)=>void;compact?:boolean}){return <div className="table-scroll"><table className="opportunity-table"><thead><tr><th>Patient</th><th>Opportunity</th>{!compact&&<th>Last activity</th>}<th>Priority</th>{!compact&&<th>Status</th>}<th><span className="sr-only">Review</span></th></tr></thead><tbody>{items.map((o,i)=><tr key={o.id} onClick={()=>onSelect(o.id)}><td><div className="patient-cell"><Avatar name={o.patient.name} index={i}/><div><button className="table-link" onClick={e=>{e.stopPropagation();onSelect(o.id);}}>{o.patient.name}</button><span>{o.patient.source_id} · {o.patient.outlet}</span></div></div></td><td><Badge tone={TYPES[o.type].color}>{TYPES[o.type].short}</Badge><span className="cell-subtitle">{o.evidence[0]?.field.replaceAll('_',' ')}: {o.evidence[0]?.value}</span></td>{!compact&&<td>{date(o.patient.last_purchase||o.patient.last_exam,true)}</td>}<td><div className="score"><span className={o.score>=75?'score-dot high':'score-dot'}/><strong>{o.score}</strong><span>{o.score>=75?'High':'Standard'}</span></div></td>{!compact&&<td><Status status={o.status}/></td>}<td><ChevronRight size={17} className="muted"/></td></tr>)}</tbody></table></div>}
export function RevenueChart({data}:{data:{date:string;revenue:number}[]}){
  const max=Math.max(...data.map(x=>x.revenue),10000); const width=620,height=170;
  const points=data.map((d,i)=>[i/(data.length-1||1)*width,height-d.revenue/max*(height-15)]);
  const line=points.map(([x,y],i)=>`${i===0?'M':'L'}${x},${y}`).join(' ');
  return <div className="revenue-chart"><div className="chart-scale"><span>{money(max)}</span><span>{money(max/2)}</span><span>$0</span></div><div className="chart-plot"><svg viewBox={`0 0 ${width} ${height+10}`} role="img" aria-label="Attributed campaign revenue by day over the last fourteen days"><defs><linearGradient id="revenue-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#c0d8a1" stopOpacity="0.65"/><stop offset="100%" stopColor="#dce9c9" stopOpacity="0.04"/></linearGradient></defs>{[0,0.5,1].map(n=><line key={n} x1="0" y1={15+n*(height-15)} x2={width} y2={15+n*(height-15)} stroke="#eaede7" strokeDasharray="4 5"/>)}<path d={`${line} L${width},${height} L0,${height}Z`} fill="url(#revenue-fill)"/><path d={line} fill="none" stroke="#668549" strokeWidth="2.5" strokeLinejoin="round"/>{points.map(([x,y],i)=><circle key={i} cx={x} cy={y} r="3" fill="#668549"><title>{date(data[i].date,true)}: {money(data[i].revenue)}</title></circle>)}</svg><div className="chart-dates">{data.filter((_,i)=>[0,4,9,13].includes(i)).map(d=><span key={d.date}>{date(d.date,true)}</span>)}</div></div></div>;
}
export function Stepper({step,labels}:{step:number;labels:string[]}){return <div className="stepper">{labels.map((label,i)=><div key={label} className={i===step?'current':i<step?'done':''}><span>{i<step?<Check size={13}/>:i+1}</span>{label}</div>)}</div>}
export function TextLink({children,onClick}:{children:ReactNode;onClick:()=>void}){return <button className="text-link" onClick={onClick}>{children}<ArrowUpRight size={15}/></button>}
